config/routes.rb
Rails.application.routes.draw do
  root to: "urls#index"
  resources :urls, only: [:index, :create]
  get "/:shortened", to: "shortened_urls#show", as: "short_url"
end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :count, presence: true
  validates :original, uniqueness: true

  def shorten(host)
    jf = ShortenUrl::JetFuel.new(host)
    digest = jf.shorten(original)
    while Url.find_by(shortened: digest)
      digest += Random.rand(0..9).to_s
    end
    digest
  end

  def shortened_url(host_with_port)
    host_with_port + "/" + shortened
  end

  def increment_count
    self.count += 1
    update(count: self.count)
  end

  def update_data(host_with_port)
    title = TitleWorker.perform_async(original)
    update(shortened: shorten(host_with_port), title: title)
  end

  def self.sort_by_popularity
    all.sort_by(&:count).reverse
  end

  def self.sort_by_date
    all.sort_by(&:updated_at).reverse
  end

  def self.update_params(original_params)
    if original_params[:original].match(/\Ahttp/)
      original_params
    else
      original_params[:original] = "http://" + original_params[:original]
      original_params
    end
  end
end

app/models/url_presenter.rb
class UrlPresenter
  attr_reader :host_with_port, :url, :urls

  def initialize(host_with_port, sort_param)
    @host_with_port = host_with_port
    @url = Url.new
    if sort_param == "popularity"
      @urls = Url.sort_by_popularity
    elsif sort_param == "date"
      @urls = Url.sort_by_date
    else
      @urls = Url.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  def show
    url = Url.find_by(shortened: params[:shortened])
    redirect_to url.original
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @url_presenter = UrlPresenter.new(request.host_with_port, params[:sort])
  end

  def create
    url = Url.find_by(url_params)
    if url
      url.increment_count
      redirect_to root_path
    else
      url = Url.new(url_params)
      if url.save
        url.update_data(request.host_with_port)
        redirect_to root_path
      else
        redirect_to root_path, notice: "Invalid url"
      end
    end
  end

  private

  def url_params
    original_params = params.require(:url).permit(:original)
    Url.update_params(original_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JetFuel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<div class="url-shortener">
  <% url = @url_presenter.url %>
  <%= form_for url do |f| %>
    <%= f.text_field :original %>
    <%= f.submit "Shorten" %>
  <% end %>
</div>

<div class="search">
  <%= text_field_tag :search %>
  <%= submit_tag "Search", id: "search-button" %>
</div>

<div class="url-stats">
  <%= link_to "Sort By Popularity", root_path(sort: "popularity") %>
  <%= link_to "Sort By Date", root_path(sort: "date") %>
  <ul>
  <% @url_presenter.urls.each do |url| %>
    <li>
      <%= url.original %> | <%= link_to url.shortened_url(@url_presenter.host_with_port), short_url_path(shortened: url.shortened) %> | <%= url.count %>
    </li>
  <% end %>
</div>